### PR TITLE
Notes final #2

### PR DESCRIPTION
**Pull request by tolyara**
Notes are ready, but photo uploading needs improvement

### CODE REVIEW

**Comment by Djubabagdad** [comment]
After handling with edit or create or update note, it returns me to ERROR_PAGE.

**Comment by Djubabagdad** [comment]
After insertting few photos, estimate general impression felt down

**Comment by Djubabagdad** [comment]
In case of opening edit information, old note info doesn't fade in.

**Comment by Djubabagdad** [comment]
Note Creation doesn't work. Country: France, City: Paris, 3 photos. After pushing on submit button -> redirect to errorPage, and note wasn't save in base.

**Comment by Djubabagdad** [comment]
Update: nullpointer exception on back

**Comment by dyominov** [comment]
Null pointer is returned (maybe it in db )

**Comment by tolyara** [comment]
> Null pointer is returned (maybe it in db )

Can you tell where exactly it returns?

**Comment by dyominov** [comment]
> > Null pointer is returned (maybe it in db )
> 
> Can you tell where exactly it returns?

When I try to get notes I get nullptr

**Comment by tolyara** [comment]
> > > Null pointer is returned (maybe it in db )
> > 
> > 
> > Can you tell where exactly it returns?
> 
> When I try to get notes I get nullptr

I got NPE only on one country - Poland. I tried to figure out what may cause this, but so far to no avail. And when you check "Only my notes" - no error. On other countries notes are working well onto my computer.
Maybe it is because my PR on backend didn't merged yet. But unlikely.
I'll try to reproduce this situation you described on the other PC.

**Comment by zhe1ezniak** [comment]
Resolve conflicts, please

**Comment by tolyara** [comment]
> Resolve conflicts, please

Conflicts resolved, but when I try to refer to endpoint http://localhost:8080/country/${country}/visit?user=${login} it returns 403. The same happens with novisit endpoint. I try to use method getLogin(), but it didn't works.

**Comment by zhe1ezniak** [comment]
You have to use method getLogin() where you need user login. Because field "login" removed from localStorage.

**Comment by zhe1ezniak** [comment]
Снимок экрана от 2019-11-26 12-15-20
But page edite note is empty.

**Comment by tolyara** [comment]
> Снимок экрана от 2019-11-26 12-15-20
> But page edite note is empty.

Yes, it is, I did not have time to output the current note data in the section edit note. But edit note mechanism works.

**Comment by zhe1ezniak** [comment]
ok

**Comment by tolyara** [comment]
> You have to use method getLogin() where you need user login. Because field "login" removed from localStorage.

I know, I use this method, but I still got 403 when I try to go to endpoint http://localhost:8080/country/${country}/visit?user=${login}. Maybe we should open an access for this endpoint (-s) on backend.

**Pull request merged**
